AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  AccountId:
    Type: String
  Region:
    Type: String
  UserName:
    Type: String
  EnvName:
    Type: String
    Default: dev
  EcrRepo:
    Type: String
    Description: ECR image Uri

Resources:
  DemoLambdaFn:
    Type: AWS::Lambda::Function
    Properties:
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/${UserName}
      PackageType: Image
      FunctionName:
        Fn::Sub: lambda-function-${EnvName}
      Code:
        ImageUri:
          Fn::Sub: ${AccountId}.dkr.ecr.${Region}.amazonaws.com/${EcrRepo}
